liveTemplates.context.file=Promela
liveTemplates.context.topLevel=Top level
liveTemplates.context.sequence=Statement sequence
liveTemplates.context.expression=Expression
group.Promela.AutomatonView.text=Automata preview actions
group.Promela.AutomatonView.description=Actions performed in the state automata editor preview.
action.Promela.AutomatonView.ReloadAction.text=Reload automaton preview
action.Promela.AutomatonView.ReloadAction.description=Recompiles the model and displays its state automata.
action.Promela.AutomatonView.ResetZoomAction.text=Reset zoom
action.Promela.AutomatonView.ResetZoomAction.description=Resets zoom to default value
action.Promela.AutomatonView.ZoomInAction.text=Zoom in
action.Promela.AutomatonView.ZoomInAction.description=Increases zoom on the state automaton
action.Promela.AutomatonView.ZoomOutAction.text=Zoom out
action.Promela.AutomatonView.ZoomOutAction.description=Decreases zoom on the state automaton
editor.AutomatonView.name=State Automata Preview
editor.AutomatonView.message.reload-to-display=Perform reload for displaying state automaton.
editor.AutomatonView.message.build-aborted=Build aborted.
editor.AutomatonView.message.model-not-found=Cannot find the compiled model, see build log for the reason why.
editor.AutomatonView.message.empty-model=Model is not containing any automata.
#Module
module.facet.name=Promela
module.builder.name=Promela
module.sdk.name=Spin SDK
module.sdk.options.cCompiler=C compiler path
#Simulation
simulation.configuration.description=Promela simulation run using built spin verifier
simulation.configuration.name=Simulation
simulation.configuration.options.trackDataValues=Track data values
simulation.configuration.options.diagramContainsStatements=Show statements in MSC
simulation.configuration.options.inheritGlobalSpinOptions=Inherit global spin options
simulation.configuration.options.fullChannel=A Full Channel
simulation.configuration.options.fullChannelBlocks=Blocks new messages
simulation.configuration.options.fullChannelLoses=Loses new messages
simulation.configuration.options.extraRuntimeOptions=Extra runtime options
simulation.configuration.options.mode=Mode
simulation.configuration.options.mode.random=Random
simulation.configuration.options.mode.random.seed=With seed:
simulation.configuration.options.mode.guided=Guided
simulation.configuration.options.mode.guided.trail=With trail:
simulation.configuration.options.mode.interactive=Interactive
simulation.configuration.options.maxSteps=Maximum number of steps
simulation.configuration.options.initialStepsSkipped=Initial steps skipped
simulation.console.values=Values
simulation.console.steps=Steps
simulation.console.step=Step
simulation.console.channels=Queues
simulation.console.interactive=Interactive
simulation.console.tab.simulation=Simulation
simulation.console.tab.console=Console
# Verification
verification.configuration.description=Promela verification run using built spin verifier
verification.configuration.name=Verification
verification.configuration.options.safety=Safety
verification.configuration.options.advancedParameters=Advanced Parameters
verification.configuration.options.memory.hint=Set this number to amount of physical (not virtual) memory\
in your system, in MegaBytes, and leave it there for all runs.\
\
 When the limit is reached, the verification is stopped to\
 avoid trashing.\
\
 If exhaustive verification cannot be completed due to\
 lack of memory, select a different storage mode.
verification.configuration.options.memory=Physical memory available
verification.configuration.options.memory.unit=Mbytes
verification.configuration.options.estimatedStateSpace=Estimated state space size
verification.configuration.options.estimatedStateSpace.hint=\
This parameter is used to calculate the size of the \
hash-table. It results in a selection of a numeric argument \
for the -w flag of the verifier. Setting it too high may \
cause an out-of-memory error with zero states reached \
(meaning that the verification could not be started). \
Setting it too low can cause inefficiencies due to \
hash collisions.<br><br> \
 \
When using bitstate, start with the default \
setting.  After a run completes successfully, \
double the estimate, and see if the number of reached \
stated changes much.  Continue to do this until \
it stops changing, or until you reach the memory bound.<br><br> \
 \
Plugin uses the closest power of two to determine the parameter \
given to the -w flag that is used for the run.
verification.configuration.options.maxSearchDepth=Maximum search depth
verification.configuration.options.maxSearchDepth.hint=\
This number determines the size of the depth-first \
search stack that is used during the verification. \
A larger number increases the memory requirements, and \
a lower number decreases it.  When there seems not to be \
sufficient memory for the search depth needed, reduce \
reduce the estimated state space size to free some \
more memory for the stack, or change the storage mode.<br><br> \
 \
If you hit the maximum search depth during a verification \
(noted as 'Search not completed' or 'Search Truncated' \
in the verification output) without finding an error, \
increase the search depth parameter and repeat the run.
verification.configuration.options.numberOfHashFunctionInBitstateMode=Number of hash functions in Bitstate mode
verification.configuration.options.numberOfHashFunctionInBitstateMode.hint=\
This number determines how many bits are set per \
state when in Bitstate verification mode. The default is 3, \
but you can use any number greater than or equal to 1. \
At the end of a Bitstate verification run, the verifier \
can issue a recommendation for a different setting of \
this parameter (specified with the -k flag), if this can \
improve coverage.
verification.configuration.options.modelGenerationOptions=Extra verifier generation options
verification.configuration.options.modelCompilationOptions=Extra compile-time options
verification.configuration.options.extraRuntimeOptions=Extra runtime options
verification.configuration.options.automatonSize=Size for minimized automaton
verification.configuration.options.automatonSize.hint=\
When using the minimized automata storage mode, you should \
set this parameter to be equal to the statevector size at first. \
At the end of the run, the verifier will then report if a smaller \
number can also be used. The smaller the number, the faster the run. \
verification.configuration.options.fullChannel=A Full Channel
verification.configuration.options.fullChannelBlocks=Blocks new messages
verification.configuration.options.fullChannelLoses=Loses new messages
verification.configuration.options.searchMode=Search Mode
verification.configuration.options.boundedContextSwitching=Bounded context switching
verification.configuration.options.boundedContextSwitchingBound=With bound
verification.configuration.options.searchMode.dfs=Depth-first search
verification.configuration.options.searchMode.bfs=Breadth-first search
verification.configuration.options.liveness=Liveness
verification.configuration.options.storageMode=Storage Mode
verification.configuration.options.neverClaims=Never Claims
verification.configuration.options.useNeverClaim.use=Use claim
verification.configuration.options.claimName=Claim name
verification.configuration.options.useNeverClaim.dontUse=Do not use a never claim or ltl property
verification.configuration.options.errorTrappingOptions=Error Trapping Options
verification.configuration.options.stopAtErrors.zero=Don't stop at errors
verification.configuration.options.stopAtErrors.some=Stop at error
verification.configuration.options.invalidEndStates=Invalid end states (deadlock)
verification.configuration.options.assertionViolations=Assertion violations
verification.configuration.options.xrXsAssertions=XR/XS assertions
verification.configuration.options.nonProgressCycles=Non-progress cycles
verification.configuration.options.acceptanceCycles=Acceptance cycles
verification.configuration.options.enforceWeakFairnessConstraint=Enforce weak fairness constraint
verification.configuration.options.computeVariableRanges=Compute variable ranges
verification.configuration.options.addComplexityProfiling=Add complexity profiling
verification.configuration.options.saveAllErrorTrails=Save all error-trails
verification.configuration.options.exhaustive=Exhaustive
verification.configuration.options.hashCompact=Hash-compact
verification.configuration.options.bitstate=Bitstate/supertrace
verification.configuration.options.minimizedAutomata=Minimized automata (slow)
verification.configuration.options.collapseCompression=Collapse compression
verification.configuration.options.iterativeSearchForShortTrail=Iterative search for short trail
verification.configuration.options.partialOrderReduction=Partial order reduction
verification.configuration.options.reportUnreachableCode=Report unreachable code
verification.configuration.options.inheritGlobalSpinOptions=Inherit global spin options
verification.configuration.options.inheritGlobalCompilationOptions=Inherit global c compiler options
# Language
language.fileType.name=Promela
language.fileType.description=Promela file
language.file.name=Promela file
language.formatting.typedefBraceStyle=Struct brace style
language.psi.error.updateFailed=Code update failed
language.psi.error.mustBeMtype=Bound element must be mtype
language.psi.error.invalidIdentifier=Invalid identifier {0}
language.psi.error.renamingMissingIdentifier=Cannot rename missing identifier
language.psi.error.renamingMacroIdentifier=Cannot rename identifier inserted by preprocessor
language.lexer.preprocessor.undefine.invalid=invalid undef format
language.lexer.preprocessor.macro.emptyArgument=empty argument
language.lexer.preprocessor.macro.unclosed=unclosed macro call
language.lexer.preprocessor.define.duplicate=duplicate definition of macro {0}
language.lexer.preprocessor.define.args.separator=comma must separate arguments
language.lexer.preprocessor.define.args.identifier=argument must be an identifier
language.lexer.preprocessor.define.args.duplicate=duplicate argument {0}
language.lexer.preprocessor.define.args.missingBracket=missing bracket at the end of the argument list
language.lexer.preprocessor.define.invalid=invalid macro definition
language.lexer.preprocessor.endif.orphan=orphaned endif
language.lexer.preprocessor.endif.invalid=invalid endif format
language.lexer.preprocessor.invalid=invalid format
language.lexer.preprocessor.elif.orphan=orphaned elif
language.lexer.preprocessor.else.orphan=orphaned else
language.lexer.preprocessor.else.invalid=invalid else format
language.lexer.preprocessor.expression.invalid.divisionByZero="division by zero"
language.lexer.preprocessor.expression.invalid.operation=invalid operation
language.lexer.preprocessor.expression.invalid.number=invalid number
language.lexer.preprocessor.expression.invalid.char=invalid char
language.lexer.preprocessor.expression.invalid.unclosed=not properly closed expression
language.lexer.preprocessor.expression.invalid.token=unexpected token in expression
language.formatting.blankLinesTopLevel=In declarations
language.lexer.preprocessor.macro.invalidArgCount=invalid number of arguments
language.psi.type.variable=variable
language.psi.type.label=label
language.psi.type.proctype=proctype
language.psi.type.typedef=type declaration
language.psi.type.inline=inline
language.psi.type.ltl=ltl
simulation.exception.missing-file=Cannot find the Promela file
simulation.exception.missing-spin=Check that the module is set
verification.exception.missing-file=Cannot find the compiled model, see build log
language.psi.error.mustBeLabel=Bound element must be label
