builder.verificationModel.name=Promela verification model builder
builder.stateTableModel.name=Promela state table model builder
build.error.compiler.io=IO exception occurred when calling {0}: {1}
build.error.spinFailed=Spin model c code generation failed with code %d
build.error.cCompilerFailed=Spin model C code compilation failed with code %d
build.error.cCompilerUnknownError=Spin model C compilation failed without any message
build.spin=Spin
build.c-compiler=C compiler